import puppeteer from 'puppeteer-core';
const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const U = 'https://kidzplayful-fe2a.vercel.app';
const b = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox'] });
const p = await b.newPage();
await p.goto(U + '/login', { waitUntil: 'networkidle2', timeout: 30000 });
await p.type('input[type=email]', 'admin@kidzplayful.app');
await p.type('input[type=password]', 'Kidz!admin2026');
await p.click('button[type=submit]');
await p.waitForFunction(() => location.pathname.startsWith('/pilih-anak'), { timeout: 30000 }).catch(() => {});
await p.goto(U + '/admin', { waitUntil: 'networkidle2', timeout: 30000 });
await new Promise(r => setTimeout(r, 1500));
const path = new URL(p.url()).pathname;
const txt = await p.$eval('body', e => e.innerText).catch(() => '');
const ok = path.startsWith('/admin') && txt.includes('Admin KidzPlayful');
console.log('URL akhir:', path);
console.log('ada panel admin:', txt.includes('Admin KidzPlayful'));
console.log('HASIL:', ok ? 'ADMIN BISA MASUK' : 'MASIH REDIRECT/PERIKSA');
await b.close();
